// The C++ exact GGML decoder against ggml b11316's own dequantize_row_* results.
//
// tests/fixtures/ggml/<format>.blocks holds whole blocks whose fields cover every grid index, sign
// pattern and scale field of the format, with binary16 scales of both zeros, subnormals, extremes,
// infinities and NaNs; <format>.f32 holds ggml-base's FP32 output for them as bit patterns
// (generated by tools/artifact/gen_ggml_fixtures.py). Equality is exact, NaN payloads included.

#include "ops/ggml_blocks_decode.h"

#include <array>
#include <bit>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

namespace {

using namespace ninfer;
namespace ggml = ninfer::test::ggml;

void require(bool condition, const std::string& message) {
    if (!condition) { throw std::runtime_error(message); }
}

std::vector<std::byte> read_file(const std::filesystem::path& path) {
    std::ifstream file(path, std::ios::binary);
    require(file.good(), "cannot open fixture " + path.string());
    std::vector<char> bytes((std::istreambuf_iterator<char>(file)), {});
    std::vector<std::byte> out(bytes.size());
    std::memcpy(out.data(), bytes.data(), bytes.size());
    return out;
}

constexpr std::array kFormats = {
    std::pair{QType::GGML_Q8_0, "ggml_q8_0"},       std::pair{QType::GGML_Q6_K, "ggml_q6_k"},
    std::pair{QType::GGML_IQ2_XXS, "ggml_iq2_xxs"}, std::pair{QType::GGML_IQ4_NL, "ggml_iq4_nl"},
    std::pair{QType::GGML_IQ3_S, "ggml_iq3_s"},     std::pair{QType::GGML_IQ2_S, "ggml_iq2_s"},
    std::pair{QType::GGML_IQ4_XS, "ggml_iq4_xs"},   std::pair{QType::GGML_IQ1_M, "ggml_iq1_m"},
    std::pair{QType::GGML_Q2_0, "ggml_q2_0"},
};

// Returns the fixture's blocks after checking every decoded bit pattern.
std::vector<std::byte> golden(QType format, const char* name) {
    const std::filesystem::path root =
        std::filesystem::path(NINFER_SOURCE_DIR) / "tests" / "fixtures" / "ggml";
    const auto blocks   = read_file(root / (std::string(name) + ".blocks"));
    const auto expected = read_file(root / (std::string(name) + ".f32"));
    const auto block    = ggml_block(format);
    const auto count    = blocks.size() / block.bytes;
    require(count >= 64 && blocks.size() == count * block.bytes &&
                expected.size() == count * block.values * 4,
            std::string(name) + ": fixture sizes disagree with the block geometry");
    const auto decoded = ggml::decode_blocks(format, blocks);
    std::size_t nan = 0;
    for (std::size_t i = 0; i < decoded.size(); ++i) {
        std::uint32_t want = 0;
        std::memcpy(&want, expected.data() + 4 * i, 4); // little-endian host
        const auto got = std::bit_cast<std::uint32_t>(decoded[i]);
        if (got != want) {
            std::ostringstream message;
            message << name << ": block " << i / block.values << " value " << i % block.values
                    << " is 0x" << std::hex << got << ", ggml has 0x" << want;
            throw std::runtime_error(message.str());
        }
        nan += (want & 0x7F800000U) == 0x7F800000U && (want & 0x7FFFFFU);
    }
    require(nan > 0, std::string(name) + ": fixture no longer reaches NaN outputs");
    std::cout << name << ": " << count << " blocks, " << decoded.size()
              << " values bit-exact (" << nan << " NaN)\n";
    return blocks;
}

// The paged layout decodes to the same values as the unpaged rows, and a non-zero tail is refused.
void paged_rows_decode_like_blocks(QType format, const std::vector<std::byte>& blocks) {
    const auto block = ggml_block(format);
    const std::uint64_t k    = block.values * 2;
    const std::uint64_t rows = blocks.size() / (2 * block.bytes);
    const std::array<std::uint64_t, 2> shape{rows, k};
    const auto flat  = weight_geometry(format, QuantLayout::GgmlBlocks, shape);
    const auto paged = weight_geometry(format, QuantLayout::GgmlRowsPage4K, shape);
    std::vector<std::byte> payload(paged.bytes);
    for (std::uint64_t row = 0; row < rows; ++row) {
        std::memcpy(payload.data() + ggml_row_offset(paged, row),
                    blocks.data() + ggml_row_offset(flat, row), flat.code_bytes_per_row);
    }
    const auto expected = ggml::decode_parent(flat, std::span(blocks).first(flat.bytes));
    const auto actual   = ggml::decode_parent(paged, payload);
    require(std::memcmp(expected.data(), actual.data(), expected.size() * 4) == 0,
            "paged rows decode differently from the same rows unpaged");
    payload.back() = std::byte{1};
    bool refused   = false;
    try {
        (void)ggml::decode_parent(paged, payload);
    } catch (const std::invalid_argument&) { refused = true; }
    require(refused, "a non-zero page tail was accepted");
}

int run() {
    for (const auto& [format, name] : kFormats) {
        const auto blocks = golden(format, name);
        paged_rows_decode_like_blocks(format, blocks);
    }
    std::cout << "GGML exact decoder matches ggml " << ninfer::ggml_tables::kRelease << '\n';
    return 0;
}

} // namespace

int main() {
    try {
        return run();
    } catch (const std::exception& error) {
        std::cerr << error.what() << '\n';
        return 1;
    }
}
