// The C++ exact GGML decoder against ggml b11316's own dequantize_row_* results.
//
// tests/fixtures/ggml/<format>.blocks holds whole blocks whose fields cover every grid index, sign
// pattern and scale field of the format, with binary16 scales of both zeros, subnormals, extremes,
// infinities and NaNs; <format>.f32 holds ggml-base's FP32 output for them as bit patterns
// (generated by tools/artifact/gen_ggml_fixtures.py). Equality is exact, NaN payloads included.

#include "ops/ggml_blocks_decode.h"

#include <array>
#include <bit>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

namespace {

using namespace ninfer;
namespace ggml = ninfer::test::ggml;

void require(bool condition, const std::string& message) {
    if (!condition) { throw std::runtime_error(message); }
}

std::vector<std::byte> read_file(const std::filesystem::path& path) {
    std::ifstream file(path, std::ios::binary);
    require(file.good(), "cannot open fixture " + path.string());
    std::vector<char> bytes((std::istreambuf_iterator<char>(file)), {});
    std::vector<std::byte> out(bytes.size());
    std::memcpy(out.data(), bytes.data(), bytes.size());
    return out;
}

constexpr std::array kFormats = {
    std::pair{QType::GGML_Q8_0, "ggml_q8_0"},       std::pair{QType::GGML_Q6_K, "ggml_q6_k"},
    std::pair{QType::GGML_IQ2_XXS, "ggml_iq2_xxs"}, std::pair{QType::GGML_IQ4_NL, "ggml_iq4_nl"},
    std::pair{QType::GGML_IQ3_S, "ggml_iq3_s"},     std::pair{QType::GGML_IQ2_S, "ggml_iq2_s"},
    std::pair{QType::GGML_IQ4_XS, "ggml_iq4_xs"},   std::pair{QType::GGML_IQ1_M, "ggml_iq1_m"},
    std::pair{QType::GGML_Q2_0, "ggml_q2_0"},
};

// Returns the fixture's blocks after checking every decoded bit pattern.
std::vector<std::byte> golden(QType format, const char* name) {
    const std::filesystem::path root =
        std::filesystem::path(NINFER_SOURCE_DIR) / "tests" / "fixtures" / "ggml";
    const auto blocks   = read_file(root / (std::string(name) + ".blocks"));
    const auto expected = read_file(root / (std::string(name) + ".f32"));
    const auto block    = ggml_block(format);
    const auto count    = blocks.size() / block.bytes;
    require(count >= 64 && blocks.size() == count * block.bytes &&
                expected.size() == count * block.values * 4,
            std::string(name) + ": fixture sizes disagree with the block geometry");
    const auto decoded = ggml::decode_blocks(format, blocks);
    std::size_t nan = 0;
    for (std::size_t i = 0; i < decoded.size(); ++i) {
        std::uint32_t want = 0;
        std::memcpy(&want, expected.data() + 4 * i, 4); // little-endian host
        const auto got = std::bit_cast<std::uint32_t>(decoded[i]);
        if (got != want) {
            std::ostringstream message;
            message << name << ": block " << i / block.values << " value " << i % block.values
                    << " is 0x" << std::hex << got << ", ggml has 0x" << want;
            throw std::runtime_error(message.str());
        }
        nan += (want & 0x7F800000U) == 0x7F800000U && (want & 0x7FFFFFU);
    }
    require(nan > 0, std::string(name) + ": fixture no longer reaches NaN outputs");
    std::cout << name << ": " << count << " blocks, " << decoded.size()
              << " values bit-exact (" << nan << " NaN)\n";
    return blocks;
}

/// Each record part decodes to its own golden blocks' values (ggml's FP32 outputs, checked by
// golden()), at the addresses the record geometry gives, and a non-zero gap is refused. Two
// experts of [hidden 256, intermediate 64]: gate and up are 64 rows of one gate/up block, down
// 256 rows of one Q2_0 block. Expert 1's parts take the fixture blocks in reverse order.
void record_parts_decode_like_blocks(QType record, const std::vector<std::byte>& gate_up,
                                     const std::vector<std::byte>& down) {
    const auto parts = ggml_record_parts(record);
    const auto g     = weight_geometry(record, QuantLayout::GgmlExpertRecord,
                                       std::array<std::uint64_t, 3>{2, 256, 64});
    const auto gu = ggml_block(parts.gate_up), d = ggml_block(parts.down);
    require(g.record_up_offset == (64 * gu.bytes + 255) / 256 * 256 &&
                g.record_down_offset == (g.record_up_offset + 64 * gu.bytes + 255) / 256 * 256 &&
                g.record_bytes == g.record_down_offset + 256 * d.bytes &&
                g.record_stride == (g.record_bytes + 255) / 256 * 256 &&
                g.bytes == 2 * g.record_stride,
            "expert record geometry differs from 256-byte aligned parts");
    std::vector<std::byte> payload(g.bytes);
    const auto blocks_of = [&](const std::vector<std::byte>& source, GgmlBlock block,
                               std::uint64_t count, bool reverse) {
        std::vector<std::byte> out(count * block.bytes);
        for (std::uint64_t i = 0; i < count; ++i) {
            const auto from = reverse ? count - 1 - i : i;
            std::memcpy(out.data() + i * block.bytes, source.data() + from * block.bytes,
                        block.bytes);
        }
        return out;
    };
    const std::array kParts = {ExpertPart::Gate, ExpertPart::Up, ExpertPart::Down};
    std::vector<std::vector<std::byte>> expected;
    for (std::uint64_t expert = 0; expert < 2; ++expert) {
        for (const auto part : kParts) {
            const bool is_down = part == ExpertPart::Down;
            auto bytes = blocks_of(is_down ? down : gate_up, is_down ? d : gu, is_down ? 256 : 64,
                                   expert == 1 || part == ExpertPart::Up);
            const auto at = ggml_record_part(g, expert, part).offset;
            std::memcpy(payload.data() + at, bytes.data(), bytes.size());
            expected.push_back(std::move(bytes));
        }
    }
    std::size_t index = 0;
    for (std::uint64_t expert = 0; expert < 2; ++expert) {
        for (const auto part : kParts) {
            const auto p        = ggml_record_part(g, expert, part);
            const auto actual   = ggml::decode_record_part(g, payload, expert, part);
            const auto reference = ggml::decode_blocks(p.format, expected[index++]);
            require(actual.size() == p.rows * p.k &&
                        std::memcmp(actual.data(), reference.data(), actual.size() * 4) == 0,
                    "an expert record part decodes differently from its blocks");
        }
    }
    payload[g.record_stride + g.record_up_offset - 1] = std::byte{1};
    bool refused = g.record_up_offset == 64 * gu.bytes; // no gap to dirty when parts align
    try {
        (void)ggml::decode_record_part(g, payload, 1, ExpertPart::Gate);
    } catch (const std::invalid_argument&) { refused = true; }
    require(refused, "a non-zero gap between record parts was accepted");
}

int run() {
    std::vector<std::vector<std::byte>> blocks;
    for (const auto& [format, name] : kFormats) { blocks.push_back(golden(format, name)); }
    const auto of = [&](QType format) -> const std::vector<std::byte>& {
        for (std::size_t i = 0; i < kFormats.size(); ++i) {
            if (kFormats[i].first == format) { return blocks[i]; }
        }
        throw std::logic_error("no fixture");
    };
    for (const auto record :
         {QType::GGML_REC_IQ2_S_Q2_0, QType::GGML_REC_IQ2_XXS_Q2_0, QType::GGML_REC_IQ1_M_Q2_0}) {
        const auto parts = ggml_record_parts(record);
        require(of(QType::GGML_Q2_0).size() >= 256 * ggml_block(QType::GGML_Q2_0).bytes,
                "the Q2_0 fixture has fewer than 256 blocks");
        record_parts_decode_like_blocks(record, of(parts.gate_up), of(parts.down));
    }
    std::cout << "GGML exact decoder matches ggml " << ninfer::ggml_tables::kRelease << '\n';
    return 0;
}

} // namespace

int main() {
    try {
        return run();
    } catch (const std::exception& error) {
        std::cerr << error.what() << '\n';
        return 1;
    }
}
