"""Regenerate tools/artifact/codecs/ggml_tables.py from ggml's ggml-common.h.

Usage: python -m tools.artifact.gen_ggml_tables PATH/TO/ggml/src/ggml-common.h [--release b11316]

The tables are ggml's (MIT, see third_party/ggml/LICENSE); this script copies them verbatim and
records the release they came from. Run it only when the pinned ggml release changes.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import re

TABLES = {
    # name: (C element type, expected element count)
    "kmask_iq2xs": ("uint8_t", 8),
    "ksigns_iq2xs": ("uint8_t", 128),
    "iq2xxs_grid": ("uint64_t", 256),
    "iq2s_grid": ("uint64_t", 1024),
    "iq3s_grid": ("uint32_t", 512),
    "kvalues_iq4nl": ("int8_t", 16),
    "iq1s_grid": ("uint64_t", 2048),
}
OUTPUT = Path(__file__).with_name("codecs") / "ggml_tables.py"

HEADER = '''"""Lookup tables of ggml's IQ block formats, copied verbatim from ggml-common.h.

Generated by tools/artifact/gen_ggml_tables.py from llama.cpp release {release}
(ggml/src/ggml-common.h). Do not edit by hand.

Copyright (c) 2023-2026 The ggml authors. Distributed under the MIT License; the full notice is in
third_party/ggml/LICENSE.
"""

GGML_RELEASE = "{release}"
'''


def _parse(source: str, name: str, ctype: str, count: int) -> list[int]:
    pattern = re.compile(
        r"GGML_TABLE_BEGIN\(\s*" + re.escape(ctype) + r"\s*,\s*" + re.escape(name)
        + r"\s*,\s*[A-Za-z0-9_]+\s*\)(.*?)GGML_TABLE_END\(\)",
        re.S,
    )
    match = pattern.search(source)
    if match is None:
        raise ValueError(f"table {name} ({ctype}) not found")
    body = re.sub(r"//[^\n]*", "", match.group(1))
    values = [int(token, 0) for token in re.findall(r"-?(?:0x[0-9a-fA-F]+|\d+)", body)]
    if len(values) != count:
        raise ValueError(f"table {name}: expected {count} values, found {len(values)}")
    return values


def render(source: str, release: str) -> str:
    lines = [HEADER.format(release=release)]
    for name, (ctype, count) in TABLES.items():
        values = _parse(source, name, ctype, count)
        width = {"uint8_t": 4, "int8_t": 4, "uint32_t": 10, "uint64_t": 18}[ctype]
        per_line = {"uint8_t": 16, "int8_t": 16, "uint32_t": 8, "uint64_t": 4}[ctype]
        if ctype == "int8_t":
            words = [str(value) for value in values]
        else:
            words = [f"0x{value:0{width - 2}x}" for value in values]
        lines.append(f"\n# {ctype} {name}[{count}]\n{name.upper()} = (\n")
        for begin in range(0, count, per_line):
            lines.append("    " + ", ".join(words[begin : begin + per_line]) + ",\n")
        lines.append(")\n")
    return "".join(lines)


def main(argv=None) -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("header", type=Path, help="ggml/src/ggml-common.h")
    parser.add_argument("--release", default="b11316")
    args = parser.parse_args(argv)
    OUTPUT.write_text(
        render(args.header.read_text(encoding="utf-8"), args.release),
        encoding="utf-8",
        newline="\n",
    )
    print(f"wrote {OUTPUT}")


if __name__ == "__main__":
    main()
